### ISSUE TITLE
Optimize Ticket Forms

### ISSUE THREAD

**Issue by ABucin** [ABucin/lite-issue-tracker-engine#38]
**Branch:** ticket-forms

**Description:** The GUI of the ticket forms needs to be optimized, since the data is too spread out.

**Tasks:**
- [x] optimize ticket management form
- [x] add ticket type to forms
- [x] optimize ticket comments form
