### ISSUE TITLE
Improved Dashboard

### ISSUE THREAD

**Issue by ABucin** [ABucin/lite-issue-tracker-engine#39]
**Branch:** improved-dashboard

**Description:** The Dashboard needs to contain more information, besides the logging and recent tickets aspect.

**Tasks:**
- [ ] update the panel toggling in the dashboard
- [ ] add workload summary
- [ ] add user information
- [ ] remove panel minimization
- [ ] add panel toggling
- [ ] change layout (1 large graph with sub-columns)

**Useful Links:**
- http://disciullodesign.wordpress.com/2011/12/08/6-steps-for-measuring-success-on-ux-projects/
