### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by ABucin** [ABucin/lite-issue-tracker-engine#40]
**Branch:** testing-capabilities

**Description:** Add testing capabilities to the project.

**Tasks:**
- [ ] add unit and integration tests through karma test runner
- [ ] find a way to test the server
- [ ] see how the tests can be run
